const actions = {
    CREATE_BOOK: 'CREATE_BOOK',
    DELETE_BOOK: 'DELETE_BOOK',
    STAR_BOOK: 'STAR_BOOK',
    SET_BOOK_SEARCH_KEY: 'SET_BOOK_SEARCH_KEY',
    SET_BOOK_STAR_FILTER: 'SET_BOOK_STAR_FILTER',

    FETCH_BOOKS_REQUEST:'FETCH_BOOKS_REQUEST',
    FETCH_BOOKS_SUCCESS: 'FETCH_BOOKS_SUCCESS',
    FETCH_BOOKS_ERROR: 'FETCH_BOOKS_ERROR',

    CREATE_BOOK_REQUEST: 'CREATE_BOOK_REQUEST',
    CREATE_BOOK_SUCCESS: 'CREATE_BOOK_SUCCESS',
    CREATE_BOOK_ERROR: 'CREATE_BOOK_ERROR'
};

export default  actions;
