const githubActions = {

	SEARCH_GITHUB_USER_REQUEST:'SEARCH_GITHUB_USER_REQUEST',
	SEARCH_GITHUB_USER_SUCCESS:'SEARCH_GITHUB_USER_SUCCESS',
	SEARCH_GITHUB_USER_ERROR:'SEARCH_GITHUB_USER_ERROR'
};

export default githubActions;
