const employeeActions = {
	ADD_EMPLOYEE: 'ADD_EMPLOYEE',
	EMPLOYEE_FORM_CHANGE: 'EMPLOYEE_FORM_CHANGE',
	ADD_EMPLOYEE_FORM_ERROR: 'ADD_EMPLOYEE_FORM_ERROR',
	REMOVE_ADD_EMPLOYEE_FORM_ERROR: 'REMOVE_ADD_EMPLOYEE_FORM_ERROR'
};

export default employeeActions;
