
const actionTypes = {
	ADD_TODO: 'ADD_TODO',
	TOGGLE_TODO: 'TOGGLE_TODO',
	SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER',

	ADD_CONTACT: 'ADD_CONTACT',
	REMOVE_CONTACT: 'REMOVE_CONTACT',
	SET_CONTACT_SEARCH_KEY: 'SET_CONTACT_SEARCH_KEY',
	SET_CONTACT_FILTER_LINK: 'SET_CONTACT_FILTER_LINK' ,
	TOGGLE_CONTACT_IMPORTANT: 'TOGGLE_CONTACT_IMPORTANT'
};

export default actionTypes;
